#include "vtrc-general-config.h"

#if VTRC_OPENSSL_ENABLED
#include "openssl/sha.h"

#ifndef SHA256_BLOCK_LENGTH
#define SHA256_BLOCK_LENGTH     64
#endif

#ifndef SHA256_DIGEST_LENGTH
#define SHA256_DIGEST_LENGTH    32
#endif

#ifndef SHA256_DIGEST_STRING_LENGTH
#define SHA256_DIGEST_STRING_LENGTH (SHA256_DIGEST_LENGTH * 2 + 1)
#endif

#ifndef SHA384_BLOCK_LENGTH
#define SHA384_BLOCK_LENGTH     128
#endif

#ifndef SHA384_DIGEST_LENGTH
#define SHA384_DIGEST_LENGTH    48
#endif

#ifndef SHA384_DIGEST_STRING_LENGTH
#define SHA384_DIGEST_STRING_LENGTH (SHA384_DIGEST_LENGTH * 2 + 1)
#endif

#ifndef SHA512_BLOCK_LENGTH
#define SHA512_BLOCK_LENGTH     128
#endif

#ifndef SHA512_DIGEST_LENGTH
#define SHA512_DIGEST_LENGTH    64
#endif

#ifndef SHA512_DIGEST_STRING_LENGTH
#define SHA512_DIGEST_STRING_LENGTH (SHA512_DIGEST_LENGTH * 2 + 1)
#endif

#else
#   include "sha2.himpl"
#endif
